export const ENDLESS_WAVES = [
  {
    id: 1,
    spawnTypes: ["fruit"],
    fruitPool: "all",
    countMin: 3,
    countMax: 4,
    spawnDelay: 0.78,
    waveDuration: 2.5,
    nextWaveDelay: 0.82,
    burstPattern: "scattered",
  },
  {
    id: 2,
    spawnTypes: ["fruit"],
    fruitPool: "all",
    countMin: 4,
    countMax: 5,
    spawnDelay: 0.68,
    waveDuration: 2.7,
    nextWaveDelay: 0.74,
    burstPattern: "line",
  },
  {
    id: 3,
    spawnTypes: ["fruit"],
    fruitPool: "all",
    countMin: 4,
    countMax: 6,
    spawnDelay: 0.6,
    waveDuration: 3.0,
    nextWaveDelay: 0.68,
    burstPattern: "arc",
  },
  {
    id: 4,
    spawnTypes: ["fruit", "fruit", "fruit", "durian"],
    fruitPool: "all",
    countMin: 5,
    countMax: 6,
    spawnDelay: 0.58,
    waveDuration: 3.1,
    nextWaveDelay: 0.62,
    burstPattern: "scattered",
  },
  {
    id: 5,
    spawnTypes: ["fruit", "fruit", "durian"],
    fruitPool: "all",
    countMin: 6,
    countMax: 7,
    spawnDelay: 0.54,
    waveDuration: 3.2,
    nextWaveDelay: 0.58,
    burstPattern: "line",
  },
  {
    id: 6,
    spawnTypes: ["fruit", "fruit", "fruit", "durian"],
    fruitPool: "all",
    countMin: 6,
    countMax: 7,
    spawnDelay: 0.5,
    waveDuration: 3.0,
    nextWaveDelay: 0.54,
    burstPattern: "arc",
  },
  {
    id: 7,
    spawnTypes: ["fruit", "fruit", "durian"],
    fruitPool: "all",
    countMin: 7,
    countMax: 8,
    spawnDelay: 0.46,
    waveDuration: 3.2,
    nextWaveDelay: 0.5,
    burstPattern: "cluster",
  },
  {
    id: 8,
    spawnTypes: ["fruit", "fruit", "fruit", "durian"],
    fruitPool: "all",
    countMin: 7,
    countMax: 8,
    spawnDelay: 0.44,
    waveDuration: 3.1,
    nextWaveDelay: 0.48,
    burstPattern: "scattered",
  },
  {
    id: 9,
    spawnTypes: ["fruit", "fruit", "durian"],
    fruitPool: "all",
    countMin: 8,
    countMax: 9,
    spawnDelay: 0.41,
    waveDuration: 3.3,
    nextWaveDelay: 0.46,
    burstPattern: "line",
  },
  {
    id: 10,
    spawnTypes: ["fruit", "fruit", "fruit", "durian"],
    fruitPool: "all",
    countMin: 8,
    countMax: 9,
    spawnDelay: 0.39,
    waveDuration: 3.2,
    nextWaveDelay: 0.44,
    burstPattern: "arc",
  },
  {
    id: 11,
    spawnTypes: ["fruit", "fruit", "durian"],
    fruitPool: "all",
    countMin: 8,
    countMax: 9,
    spawnDelay: 0.37,
    waveDuration: 3.4,
    nextWaveDelay: 0.42,
    burstPattern: "cluster",
  },
  {
    id: 12,
    spawnTypes: ["fruit", "fruit", "fruit", "durian", "durian"],
    fruitPool: "all",
    countMin: 9,
    countMax: 10,
    spawnDelay: 0.35,
    waveDuration: 3.4,
    nextWaveDelay: 0.4,
    burstPattern: "scattered",
  },
];
