export const SUNSET_WAVES = [
  { id: 1, spawnTypes: ["fruit"], fruitPool: "all", countMin: 2, countMax: 2, spawnDelay: 1.2, waveDuration: 4.0, nextWaveDelay: 2.0, burstPattern: "scattered" },
  { id: 2, spawnTypes: ["fruit"], fruitPool: "all", countMin: 2, countMax: 3, spawnDelay: 1.12, waveDuration: 4.0, nextWaveDelay: 1.9, burstPattern: "arc" },
  { id: 3, spawnTypes: ["fruit"], fruitPool: "all", countMin: 2, countMax: 3, spawnDelay: 1.05, waveDuration: 4.1, nextWaveDelay: 1.8, burstPattern: "line" },
  { id: 4, spawnTypes: ["fruit"], fruitPool: "all", countMin: 3, countMax: 3, spawnDelay: 0.98, waveDuration: 4.2, nextWaveDelay: 1.7, burstPattern: "scattered" },
  { id: 5, spawnTypes: ["fruit"], fruitPool: "all", countMin: 3, countMax: 4, spawnDelay: 0.94, waveDuration: 4.3, nextWaveDelay: 1.6, burstPattern: "cluster" },
  { id: 6, spawnTypes: ["fruit", "fruit", "durian"], fruitPool: "all", countMin: 3, countMax: 4, spawnDelay: 0.9, waveDuration: 4.4, nextWaveDelay: 1.5, burstPattern: "arc" },
  { id: 7, spawnTypes: ["fruit", "fruit", "durian"], fruitPool: "all", countMin: 4, countMax: 4, spawnDelay: 0.86, waveDuration: 4.4, nextWaveDelay: 1.45, burstPattern: "line" },
  { id: 8, spawnTypes: ["fruit", "fruit", "durian"], fruitPool: "all", countMin: 4, countMax: 5, spawnDelay: 0.8, waveDuration: 4.5, nextWaveDelay: 1.4, burstPattern: "scattered" },
  { id: 9, spawnTypes: ["fruit", "fruit", "fruit", "durian"], fruitPool: "all", countMin: 4, countMax: 5, spawnDelay: 0.76, waveDuration: 4.5, nextWaveDelay: 1.35, burstPattern: "cluster" },
  { id: 10, spawnTypes: ["fruit", "fruit", "durian"], fruitPool: "all", countMin: 5, countMax: 5, spawnDelay: 0.72, waveDuration: 4.6, nextWaveDelay: 1.3, burstPattern: "arc" },
  { id: 11, spawnTypes: ["fruit", "fruit", "durian"], fruitPool: "all", countMin: 5, countMax: 6, spawnDelay: 0.68, waveDuration: 4.6, nextWaveDelay: 1.25, burstPattern: "line" },
  { id: 12, spawnTypes: ["fruit", "fruit", "fruit", "durian"], fruitPool: "all", countMin: 5, countMax: 6, spawnDelay: 0.64, waveDuration: 4.7, nextWaveDelay: 1.2, burstPattern: "scattered" },
  { id: 13, spawnTypes: ["fruit", "fruit", "durian"], fruitPool: "all", countMin: 6, countMax: 6, spawnDelay: 0.6, waveDuration: 4.8, nextWaveDelay: 1.16, burstPattern: "cluster" },
  { id: 14, spawnTypes: ["fruit", "fruit", "fruit", "durian"], fruitPool: "all", countMin: 6, countMax: 7, spawnDelay: 0.58, waveDuration: 4.8, nextWaveDelay: 1.1, burstPattern: "arc" },
  { id: 15, spawnTypes: ["fruit", "fruit", "durian"], fruitPool: "all", countMin: 6, countMax: 7, spawnDelay: 0.56, waveDuration: 4.8, nextWaveDelay: 1.05, burstPattern: "line" },
  { id: 16, spawnTypes: ["fruit", "fruit", "fruit", "durian"], fruitPool: "all", countMin: 7, countMax: 7, spawnDelay: 0.54, waveDuration: 4.9, nextWaveDelay: 1.0, burstPattern: "scattered" },
  { id: 17, spawnTypes: ["fruit", "fruit", "durian"], fruitPool: "all", countMin: 7, countMax: 8, spawnDelay: 0.52, waveDuration: 5.0, nextWaveDelay: 0.95, burstPattern: "cluster" },
  { id: 18, spawnTypes: ["fruit", "fruit", "fruit", "durian"], fruitPool: "all", countMin: 7, countMax: 8, spawnDelay: 0.5, waveDuration: 5.0, nextWaveDelay: 0.9, burstPattern: "arc" },
  { id: 19, spawnTypes: ["fruit", "fruit", "durian"], fruitPool: "all", countMin: 8, countMax: 8, spawnDelay: 0.48, waveDuration: 5.0, nextWaveDelay: 0.86, burstPattern: "line" },
  { id: 20, spawnTypes: ["fruit", "fruit", "fruit", "durian", "durian"], fruitPool: "all", countMin: 8, countMax: 9, spawnDelay: 0.44, waveDuration: 5.2, nextWaveDelay: 0.8, burstPattern: "scattered" },
];
