export const CONFIG = {
  mediaPipeVisionUrl:
    "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/vision_bundle.mjs",
  mediaPipeWasmRoot:
    "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm",
  mediaPipeHandModel:
    "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task",
  mediaPipeSegmentationModel:
    "https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_segmenter_landscape/float16/latest/selfie_segmenter_landscape.tflite",

  minHandConfidence: 0.3,
  handDetectFps: 60,
  trailMaxPoints: 20,
  trailDecayMs: 400,
  sliceVelocityThreshold: 280,
  trailMinDistance: 2,
  trailWidth: 16,
  handSmoothing: 0.42,
  handFastSmoothing: 0.84,
  handFastVelocity: 900,
  handLostHoldMs: 90,
  handPredictionMs: 70,
  handMatchDistance: 220,
  minHandSeparation: 110,
  trailLitePointFactor: 0.55,
  trailLiteDistanceMultiplier: 1.5,
  sliceCollisionPadding: 28,
  slicePathRadius: 24,
  sliceBladeHalfWidth: 18,
  sliceBladeBackOffset: 12,
  spawnDelayMultiplier: 1,
  waveDelayMultiplier: 1,
  segmentationIntervalMs: 33,
  liteSegmentationIntervalMs: 50,
  segmentationEnabled: true,
  maskAlphaThreshold: 0.52,
  maskAlphaFeather: 0.18,
  maskTemporalSmoothing: 0.14,
  maskEdgeBlurPx: 2,
  maskErodePasses: 0,
  liteParticleFactor: 0.5,
  liteBackgroundTint: "rgba(22, 24, 18, 0.14)",
  introPlayerMaxHeightRatio: 0.46,
  introPlayerMaxWidthRatio: 0.58,
  introPlayerBottomInsetRatio: 0.08,

  fruitBaseSize: 120,
  gravity: 900,
  fruitSpawnYOffset: 100,
  fruitCullPadding: 180,
  fruitArcPeakVariance: 0.3,
  bowlGravity: 1200,
  bowlCompositionPassDurationMs: 600,

  particleGravity: 860,
  particleLifeMs: 800,
  particleMinSize: 3,
  particleMaxSize: 8,
  particleBaseCount: 16,

  maxDurianHits: 3,
  hudPadding: 28,
  hudFont: "24px system-ui, sans-serif",
  scoreFont: "600 28px system-ui, sans-serif",
  overlayTitleFont: "700 58px system-ui, sans-serif",
  overlayTextFont: "400 26px system-ui, sans-serif",
  overlayButtonFont: "700 34px system-ui, sans-serif",
  gameOverFadeMs: 700,
  restartSwipeDelayMs: 900,
  openingPromptMs: 1200,
  calibrationHoldMs: 2000,
  modeHoverMs: 900,
  endlessLives: 3,
  timedDurationMs: 90_000,
  sunsetDurationMs: 5 * 60_000,
  sunsetMinDurationMs: 5 * 60_000,
  sunsetMaxDurationMs: 8 * 60_000,
  idleThresholdMs: 15_000,
  idleMovementThreshold: 16,
  idleFireflySpawnRate: 0.3,
  birdSpawnMinMs: 30_000,
  birdSpawnMaxMs: 60_000,
  bowlRevealStaggerMs: 35,
  bowlRadius: 210,
  bowlCenterYRatio: 0.63,
  bowlFruitPadding: 0.9,
  durianWarnHumFreq: 80,
  hazeAmplitude: 2,
  hazeWavePeriodMs: 4000,
  hazeBandCount: 4,
  hazeEnabled: true,
  targetFps: 60,
  liteFpsThreshold: 34,
  liteRecoverFpsThreshold: 42,
  liteWindowMs: 3000,
  environmentPlaybackStallMs: 1400,
  environmentPlaybackEpsilon: 0.02,

  flashDecayPerSecond: 3.5,
  playerTint: "rgba(255,255,255,0.08)",

  webcamConstraints: {
    audio: false,
    video: {
      facingMode: "user",
      width: { ideal: 960, max: 960 },
      height: { ideal: 540, max: 540 },
      frameRate: { ideal: 60, max: 60 },
    },
  },

  handColors: {
    Left: "#6bdcff",
    Right: "#ff9f6b",
    default: "#ffffff",
  },
};
